# version: '3.7'
services:
    eureka-server:
        build: .
        restart: always
        ports:
            - 8761:8761
        networks:
            - share-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_INSTANCE_HOSTNAME=eureka-server
            - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
            - EUREKA_CLIENT_FETCH_REGISTRY=false
        # depends_on:
        #     - mysqldb

        volumes:
            - .m2:/root/.m2

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - '2181:2181'
        networks:
            - share-network

    kafka:
        image: confluentinc/cp-kafka:7.8.0
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_MAX_REQUEST_SIZE: 20971520 # 20MB
            KAFKA_MESSAGE_MAX_BYTES: 20971520 # 20MB
        networks:
            - share-network
        links:
            - zookeeper:zookeeper
networks:
    share-network:
        external: true
