
###
GET http://{{host}}/api/v1/books/1 HTTP/1.1
###
GET http://{{host}}/api/v1/books/all HTTP/1.1




# // Add book POST /api/v1/books
# @PostMapping("/")
# BookEntity newEntity(@RequestBody BookEntity entity) {
# return repository.save(entity);
# }
###
# @name new_book 
POST http://{{host}}/api/v1/books HTTP/1.1
Content-Type: application/json

{ 
    "name": "fake content",
    "author" : "fake content"
}

@id_new_book = {{new_book.response.body.id}}

###
GET http://{{host}}/api/v1/books/{{id_new_book}} HTTP/1.1

# 4ceba4c4-40a4-4477-aa9d-53cb2ff245d6
###
PUT  http://{{host}}/api/v1/books/{{id_new_book}} HTTP/1.1
Content-Type: application/json

{ 
    "name": "update content",
    "author" : "update content"
}

###
DELETE http://{{host}}/api/v1/books/{{id_new_book}} HTTP/1.1


###
GET http://{{host}}/api/v1/employees/1 HTTP/1.1

###
# this.firstName = firstName;
# this.lastName = lastName;
# this.KIN = KIN;
# this.isDiscipilined = isDiscipilined;
# @name new_book 
POST http://{{host}}/api/v1/employees HTTP/1.1
Content-Type: application/json

{ 
    "firstName" : "firstName",
    "lastName" : "lastName",
    "KIN" : "KIN",
    "isDiscipilined" : false
}

@id_new_book = {{new_book.response.body.id}}

###
GET http://{{host}}/api/v1/employees/{{id_new_book}} HTTP/1.1

# 4ceba4c4-40a4-4477-aa9d-53cb2ff245d6
###
PUT  http://{{host}}/api/v1/employees/{{id_new_book}} HTTP/1.1
Content-Type: application/json

{ 
     "firstName" : "firstName1",
    "lastName" : "lastName2",
    "KIN" : "KIN2",
    "isDiscipilined" : true
}

###
DELETE http://{{host}}/api/v1/employees/{{id_new_book}} HTTP/1.1

###
// Get borrowed books for employee GET /api /v1/employees/{employeeId}/books
GET http://{{host}}/api/v1/employees/2/books HTTP/1.1



###

# add book
# ("Tuổi thơ dữ dội - Tập 1","Phùng Quán",1),
# ("Astérix - Astérix và cái vạc","René Goscinny",1),
# ("Momo, Hoàng tử bé xóm Cúc Lam","Yaël Hassan",1),
# ("Khi 'trai' đẹp hẹn hò - Tập 2 (Tặng Set 2 Bookmark Ghép Hình)","Nana Aokawa",1),
# ("Dế mèn phiêu lưu ký","Tô Hoài",1),
# ("Doraemon Movie Story màu - Nobita và bản giao hưởng Địa Cầu","Fujiko F Fujio",1);

POST http://{{host}}/api/v1/books HTTP/1.1
Content-Type: application/json

{ 
    "name": "fake content",
    "author" : "fake content"
}

###
@hostname = 127.0.0.1
@port = 8080
@host = {{hostname}}:{{port}}


###
get http://{{host}}/api/v1/borrowing/all HTTP/1.1
###
get http://{{host}}/api/v1/books/all HTTP/1.1
###
get http://{{host}}/api/v1/employees/all HTTP/1.1
###
// Add a new borrowing POST /api/v1/borrowing
POST http://{{host}}/api/v1/borrowing HTTP/1.1
Content-Type: application/json

{ 
     "book": {
      "id": "1",
      "name": "Búp sen xanh",
      "author": "son tung",
      "isReady": false
     },
    "employee": {
        "id":"1",
        "firstName":"A",
        "lastName":"Le van",
        "isDiscipilined":false
    }
}


###
@hostname = 127.0.0.1
@port = 8080
@host = {{hostname}}:{{port}}

# ------------------------NOTE-------------------------
###
GET http://{{host}}/api/v1/books/all
###
GET http://{{host}}/api/v1/employees/all
###
GET http://{{host}}/api/v1/borrowing/all
# ------------------------END NOTE--------------------- 
#==================
# Get book borrowing by employee	GET	/api/v1/borrowing/{employeeId}
#==================
###
@employeeId = 2
GET http://{{host}}/api/v1/borrowing/{employeeId} HTTP/1.1
###
#==================
