# version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8083:8083
        networks:
            - borrowing-net
            - share-network
        environment:
            - spring.datasource.url=jdbc:mysql://mysqldb:3306/borrowing?allowPublicKeyRetrieval=true
            - SPRING_DEVTOOLS_REMOTE_DEBUG=true
            - JAVA_OPTS=-Dspring.devtools.restart.enabled=true
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

        depends_on:
            - mysqldb

        volumes:
            - .m2:/root/.m2
            - ./src:/app/src
            - ./target:/app/target
        command: mvn spring-boot:run

    mysqldb:
        image: 'mysql:8.0'
        restart: always
        # ports:
        #   - 3306:3306
        expose:
            - 3306
        networks:
            - borrowing-net
        environment:
            MYSQL_DATABASE: borrowing
            MYSQL_USER: user1
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
networks:
    borrowing-net:
    share-network:
        external: true
