# version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8081:8081
        networks:
            - book-net
            - share-network
        environment:
            - spring.datasource.url=jdbc:mysql://mysqldb:3306/book?allowPublicKeyRetrieval=true
            - SPRING_DEVTOOLS_REMOTE_DEBUG=true
            - JAVA_OPTS=-Dspring.devtools.restart.enabled=true
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
            - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
        depends_on:
            - mysqldb

        volumes:
            - .m2:/root/.m2 # Cache Maven dependencies
            - ./src:/app/src # Đồng bộ mã nguồn
            - ./pom.xml:/app/pom.xml # Đồng bộ file pom.xml
        command: mvn spring-boot:run # Chạy ứng dụng Spring Boot với Maven (hot reload)
    mysqldb:
        image: 'mysql:8.0'
        restart: always
        # ports:
        #   - 3306:3306
        expose:
            - 3306
        networks:
            - book-net
        environment:
            MYSQL_DATABASE: book
            MYSQL_USER: user1
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
networks:
    book-net:
    share-network:
        external: true
